### ISSUE TITLE
npm issue

### ISSUE THREAD

**Issue by jithivk** [anthonykirby/lora-packet#93]
Showing error while installing lora decoder using npm

**Comment by anthonykirby** [comment]
I've checked that it installs from npm:
```
anthonykirby:~/tmp$ npm install lora-packet

added 18 packages, and audited 19 packages in 557ms

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
lora-packet is a stable package (6 years old), with few recent changes.  Of course it is possible that a regression has occurred (e.g. due to dependencies), but there's literally nothing I can do if all the issue says is "showing error".  
Please search for "how to write a good bug report", or read https://marker.io/blog/how-to-write-bug-report
